### ISSUE TITLE
bad VID header

### ISSUE THREAD

**Issue by ScApi** [Quallenauge/Easybox-904-XDSL#1]
As I'm trying to port You're repo to LTE  version, I've came across some strange issue with sysupgrade.

I'm keep getting 

> [    5.039991] ubi0 error: 0x80339140: bad VID header offset 2048, expected 512
> [    5.046438] ubi0 error: 0x8033919c: bad EC header
> [    5.051085] Erase counter header dump:
> [    5.054857]  magic          0x55424923
> [    5.058532]  version        1
> [    5.061535]  ec             3
> [    5.064518]  vid_hdr_offset 2048
> [    5.067716]  data_offset    4096
> [    5.070962]  image_seq      375226156
> [    5.074591]  hdr_crc        0xca819103

Can You point why this is happening ? Did You came across something similar ?

**Comment by Quallenauge** [comment]
The standard setup for UBI isn't working for the LTE variant of the device (it seems).
So I added a parameter to force 2048 header. Have a look at:
https://github.com/Quallenauge/Easybox-904-XDSL/blob/master-lede/target/linux/lantiq/base-files/lib/upgrade/platform.sh#L18
and
https://github.com/Quallenauge/Easybox-904-XDSL/blob/master-lede/package/base-files/files/lib/upgrade/nand.sh#L130
Maybe you need other values (or none of them). Also take into account, that ubifs isn't supported by the official OpenWRT branch anymore. So, I'm curious if squashfs is working for your device.

**Comment by ScApi** [comment]
As I'm trying to go with squashfs but it fails at mount (cannot find root filesystem), but question, as it is ubizined it still needs ubi related bootargs ? or am I wrong ?

**Comment by Quallenauge** [comment]
I tried squashfs and was surprised how well this works. A sysupgrade went well. Only the bootargs have to be adapted: Actually I use:
`bootargs = "console=ttyLTQ0,115200 ubi.mtd=12,2048 panic=1 DTS-TEST-SEQNO=77 root=/dev/ubiblock0_0 rootdelay=7 mem=116M phym=128M vpe1_load_addr=0x87e00000 vpe1_mem=2M maxvpes=1 maxtcs=1 nosmp";`
Note the **root=/dev/ubiblock0_0** and the removed **rootfs** parameter (compared to the old used one).

**Comment by ScApi** [comment]
Thx, now it works, I've made stupid mistake by typo in board name in platform_pre_upgrade, and it didn't set correct VID, as I'll debug all of this and fix bugs will make PR

**Comment by ScApi** [comment]
Another problem, after starting without enabled wifi I get something like this from log

> [ 5596.367055] timeout(2 secs): cmd=8b01 no response

> [ 5598.383041] timeout(2 secs): cmd=8b01 no response

**Comment by Quallenauge** [comment]
Maybe you can open another issue for this topic.
Include some details, like dmesg messages.
Does it work with wlan turned on?

**Comment by ScApi** [comment]
Resolved
