### ISSUE TITLE
Wifi init problem

### ISSUE THREAD

**Issue by ScApi** [Quallenauge/Easybox-904-XDSL#2]
Full bootlog in here https://pastebin.com/68QY9H9E

Constant spam of  `[  267.417574] WARN! IOCTL 8b21 ignored (interface not opened yet)`
Cannot turn radio on, ends with :

```
Shutdown interface wl000
Invalid command : set
Invalid command : set
Invalid command : set
scan device: wl010
Shutdown interface wl010
Invalid command : set
Invalid command : set
Invalid command : set
scan device: wl000
Enable device wl000
DEVICE: wl000 VIF: default_wl000
Encryption: psk2+aes
Preparing interface <wl000>

Bring up interface <wl000> to be able to send iwpriv commands
Configure wifi device wl000

Starting wifi device wl000
iwpriv 'wl000' set Enable=1; iwpriv 'wl000' set Enable=0; iwpriv 'wl000' set RadioOn=0; iwpriv 'wl000' set AuthMode=WEPAUTO; iwpriv 'wl000' set EncrypType=WEP; iwpriv 'wl000' set IEEE8021X=0; echo 'wl000' is WPA2-AES MODE; iwpriv 'wl000' set AuthMode=WPA2PSK; iwpriv 'wll000' set EncrypType=AES; iwpriv 'wl000' set IEEE8021X=0; iwpriv 'wl000' set WPAPSK='WiFipassword'; iwpriv 'wl000' set DefaultKeyID=2; iwpriv 'wl000' set SSID=Lede ; iwpriv 'wl000' set Enable=1; iwpriv 'wl000' set RadioOn=1
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
wl000 is WPA2-AES MODE
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
wl000(ralink): enable failed
scan device: wl010
Enable device wl010
DEVICE: wl010 VIF: default_wl010
Encryption: psk2+aes
Preparing interface <wl010>

Bring up interface <wl010> to be able to send iwpriv commands
Configure wifi device wl010

Starting wifi device wl010
iwpriv 'wl010' set Enable=1; iwpriv 'wl010' set Enable=0; iwpriv 'wl010' set RadioOn=0; iwpriv 'wl010' set AuthMode=WEPAUTO; iwpriv 'wl010' set EncrypType=WEP; iwpriv 'wl010' set IEEE8021X=0; echo 'wl010' is WPA2-AES MODE; iwpriv 'wl010' set AuthMode=WPA2PSK;iwpriv 'wl010' set EncrypType=AES; iwpriv 'wl010' set IEEE8021X=0; iwpriv 'wl010' set WPAPSK='WiFipassword'; iwpriv 'wl010' set DefaultKeyID=2; iwpriv 'wl010' set SSID=Lede1 ; iwpriv 'wl010
' set Enable=1; iwpriv 'wl010' set RadioOn=1
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
wl010 is WPA2-AES MODE
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
Invalid command : set
wl010(ralink): enable failed
```

**Comment by ScApi** [comment]
I assume it has something to do with 
`ERROR! can't get target's MAC address, boot fail.`

But don't know how this driver works

**Comment by Quallenauge** [comment]
Indeed, it seems the wlan subsystem isn't able to communicate with the iNIC hardware.
I can only speak for the Easybox-904-XDSL: The hw is connected to an switch of the port and communicates via ethernet messages. In the case of the 904-XDSL device, the right gpio has to be switched on, then there where broadcast messages from the bootloader. These message can be made visible by an tcpdump. Does these messages occur?
This is the precondition for next steps of initializing the wlan.

**Comment by ScApi** [comment]
Thanks for pointing that out, need to test it tomorow, on LTE version reset gpio is 30 so reset_gpio=492 in case if platform is lantiq,mrl952akw33-e-ir

**Comment by ScApi** [comment]
And another problem, gpio 30 is used in your config for TP, but LTE version doesn't use SIPO_GPIO at all.
Difficult device to work with so much cut down sources.

**Comment by Quallenauge** [comment]
Maybe you can check the configuration of the Openwrt vendor package. Sometimes, there is an hint about used gpios.

**Comment by Quallenauge** [comment]
On a step by step analysis, you can modify the stock kernel and print out the gpio actions (as I did it for the xdsl device) and load the services step by step.
The gpio driver of the stock kernel gives you an overview about the used gpios and their state via debug files within the /proc folder if I'm remember correctly.
I don't know how you develop the image, but I pushed an image to an attached sdcard and load the stock kernel via tftp. (Therefore I had to modify the uboot kernel arguments (rootfs=/device/sda) ). This speeds up development a little bit, by comparing the stock behavior to the development behavior.

**Comment by ScApi** [comment]
Ok, I've found source of all of this, init fails and later on disables any communication if nothing is plugged to lan port, on Your dts it's fixed by port status and speed bypass for realtek switch communication, need to find some elegant way to keep interface up even if nothing is plugged.
