### ISSUE TITLE
Touchpad driver

### ISSUE THREAD

**Issue by ScApi** [Quallenauge/Easybox-904-XDSL#3]
As LTE version dosn't use SIPO for TP, and Your driver uses it by default can You make it driver independent, or dependent on dts settings ?

**Comment by Quallenauge** [comment]
You mean the gpio calls?
They seem to activate the i2c bus. Does it hurts the LTE device, or are they "only" useless?

**Comment by ScApi** [comment]
It works but only with dummy gpios in dts, SIPO is simply useless in LTE version.
